version: '3'

services:
    app:
        image: camaradeputados
        volumes:
            - camaradeputados_data:/var/lib/etl
        links: 
            - db
            
    db:
        container_name: db
        image: postgres:12.1
        restart: always
        environment:
            POSTGRES_PASSWORD: '123'
            POSTGRES_DATABASE: deputados
        ports:
            - "15432:5432"
        volumes:
            - sql_data:/var/lib/sql
        networks:
            - postgres-compose-network

    adminer:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "douglasmartinsbraga@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123"
        links:
            - db
        ports:
            - "16543:80"
        depends_on:
            - db
        networks:
            - postgres-compose-network
          

    metabase:
        image: metabase/metabase:latest
        links:
            - db
        ports:
            - 3000:3000
        volumes:
            - metabase_data:/var/lib/metabase

volumes:
    camaradeputados_data:
    sql_data:
    metabase_data:

networks: 
    postgres-compose-network:
        driver: bridge