version: '3'

services:
    postgres:
        image: postgres:12.1
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: '123'
            POSTGRES_DB: deputados
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ./app/input:/app/input

    airflow:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:123@postgres/deputados
        volumes:
            - ./app/scripts/dags:/usr/local/airflow/dags
            - ./app:/app
        ports:
            - "8080:8080"

    metabase:
        image: metabase/metabase:latest
        depends_on:
            - postgres
        ports:
            - 3000:3000
        volumes:
            - ./metabase_data:/metabase.db

volumes:
    postgres_data: 
        external: true
    metabase_data: 
        external: true